### ISSUE TITLE
Unable to run tests, annotated with @DataSupplier, from IDE 

### ISSUE THREAD

**Issue by JustAlexOne** [sskorol/test-data-supplier-maven-example#1]
Done all necessary setup to apply @DataSupplier.
And everything works fine when running tests with build tool (Maven in my case).
But when running tests with IDE (Run as...), it fails.
I annotated my test class with `@Listeners(DataProviderTransformer.class)`, but still no luck.

Here is my minimum code:
```
@Listeners(DataProviderTransformer.class)
public class TestSupplier extends BaseSupplier {

    @Test(dataProvider = "provider")
    public void test1(String param) throws Exception {
        System.out.println(param);
    }

    @DataSupplier
    public List<String> provider() {
        return ImmutableList.of("A", "B", "C", "D");
    }

}
```
Stacktrace:
```
[Utils] [ERROR] [Error] org.testng.TestNGException: 
Method public void com.test.TestSupplier.test1(java.lang.String) throws java.lang.Exception requires a @DataProvider named : provider
	at org.testng.internal.Parameters.findDataProvider(Parameters.java:336)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:498)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1308)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1036)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1126)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:127)
```

**Comment by sskorol** [comment]
@JustAlexOne,

When you run via IDE, tmp configuration is created for you. In this case you should manually provide listener the following way:

![image](https://user-images.githubusercontent.com/6638780/28259704-3caea888-6ae0-11e7-9633-79ead3ce8858.png)
